In [13]:
## Steps to reproduce
# 1: Import numpy, pandas, XGBRegressor.
# 2: Define a custom objective function. Arguments (y_true, y_pred), return values (grad, hess).
#     When reg.predict(X) runs, the gradient computed by the objective function logcoshobj is printed, and is non-zero.
# 3: Create a XGBRegressor object with argument "objective" set to the custom objective function.
# 4: Fit a small dataset to a small result set, and predict on the same dataset, expecting a result similar to the result set.


import numpy as np
import pandas as pd
from xgboost import XGBRegressor


def logcoshobj(y_true, y_pred):
    grad = np.tanh(y_true - y_pred)
    hess = 1.0 - grad*grad
    print(grad)
    return grad, hess


def zero_obj(y_true, y_pred):
    length = len(y_true)
    return np.zeros(length), np.zeros(length)


def one_obj(y_true, y_pred):
    length = len(y_true)
    return np.ones(length), np.ones(length)


X = pd.DataFrame([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
Y = pd.DataFrame([[1], [2], [3]])
reg = XGBRegressor(objective=logcoshobj)
# reg = XGBRegressor(objective=one_obj)
# reg = XGBRegressor(objective=zero_obj)

reg.fit(X, Y)
reg.predict(X)

# Result is the same as running with objective=zero_obj, although the `grad` and `hess` computed are non-zero. Also, `grad` and `hess` do not change between different calls to logcoshobj.
# Result is different when compared to running with objective=one_obj.


[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717  0.90514827  0.98661429]
[ 0.46211717

array([ 0.5,  0.5,  0.5], dtype=float32)